---
_extends: .github

repository:
  name: jvm-toxcore-api
  description: The base Tox4j API without any implementation
  topics: tox, java, scala
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - bazel-opt
          - Codacy Static Code Analysis
          - code-review/reviewable
