---
cirrus-ci_task:
  container:
    image: toxchat/toktok-stack:0.0.11
    cpu: 2
    memory: 4G
  configure_script:
    - /src/workspace/tools/inject-repo jvm-toxcore-api
  test_all_script:
    - bazel test -k
        --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
        --config=release
        //jvm-toxcore-api/...
